version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: guruhub-postgres
    restart: always
    environment:
      POSTGRES_USER: guruhub_user
      POSTGRES_PASSWORD: guruhub_password
      POSTGRES_DB: guruhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
